version: '2.3'

services:
    mysql:
        container_name: mysqldatabase
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: martinalbert
            MYSQL_PASSWORD: root
        command: mysqld --init-file="/tmp/database/init.sql"
        volumes:
            - ./docker/data:/tmp/database
        ports:
            - '3306:3306'
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 10s
            retries: 10

    server:
        container_name: rest-api
        restart: always
        build:
            context: ./server
            dockerfile: DockerFile
        volumes:
            - /usr/src/app/server/node_modules/
        ports:
            - 3000:3000
        environment:
            - CURRENT_DATABASE=mysql
            - MYSQL_URL=mysqldatabase
            - MYSQL_PORT=3306
            - MYSQL_DB=database
            - MYSQL_USER=martinalbert
            - MYSQL_PW=root
            - JWT_SECRET=x23f_
            - MYSQL_SOCKET=/var/run/mysqld/mysqld.sock
        depends_on:
            mysql:
                condition: service_healthy
        links:
            - mysql

    service:
        container_name: microservice
        restart: always
        build:
            context: ./service
            dockerfile: DockerFile
        environment:
            - CURRENT_DATABASE=mysql
            - RESTAPI_URL=http://rest-api:3000
            - PORT=3000
            - JWT_SECRET=x23f_
        depends_on:
            mysql:
                condition: service_healthy
