version: '3'

services:
    mysql:
        container_name: mysqldatabase
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        command: --character-set-server=utf8mb4
        ports:
            - '3306:3306'
        restart: always

    server:
        container_name: rest-api
        restart: always
        build:
            context: ./server
            dockerfile: DockerFile
        volumes:
            - ./server:/usr/src/app/server
        ports:
            - 3000:3000
        environment:
            - CURRENT_DATABASE=mysql
            - MYSQL_URL=mysqldatabase
            - MYSQL_PORT=3306
            - MYSQL_DB=database
            - MYSQL_USER=root
            - MYSQL_PW=root
            - JWT_SECRET=x23f_
            - MYSQL_SOCKET=/var/run/mysqld/mysqld.sock
        links:
            - mysql
        depends_on:
            - mysql

    service:
        container_name: microservice
        restart: always
        build:
            context: ./service
            dockerfile: DockerFile
        volumes:
            - ./service:/usr/src/app/service
        environment:
            - CURRENT_DATABASE=mysql
            - RESTAPI_URL=http://rest-api:3000
            - PORT=3000
            - JWT_SECRET=x23f_
        depends_on:
            - server
